config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :vendor_interfaces, :member => {:small_show => :get }

  map.resources :device_configs
  map.resources :vendor_interfaces

  map.resources :report_types, :member => { :copy => :get }

  map.resources :reports, :member => { :copy => :get, :sail_jnlp => :get, :otml => :get }
  map.resources :reports do |report|
    report.resources :report_types    
  end

  map.resources :otrunk_report_templates, :member => { :copy => :get, :usage => :get, :otml => :get }
  
  map.resources :calibrations, :member => { :copy => :get }
  map.calibrations '/calibrations/data_filter_parameters', :controller => "calibrations", :action => 'data_filter_parameters'
  map.resources :calibrations

  map.resources :data_filters, :member => { :copy => :get }

  map.resources :probes, :member => { :copy => :get }

  map.resources :physical_units, :member => { :copy => :get }

  map.resources :probe_types do |probe_types|
    probe_types.resources :calibrations, :member => { :copy => :get }
  end

  map.resources :model_types, :member => { :copy => :get }

  map.resources :learners, :member => { :sessions => :get }
  map.resources :learners, :member => { :ot_learner_data => :get }

  map.resources :units do |units|
    units.resources :activities, :name_prefix => "unit_"
  end

  map.resources :subjects do |subjects|
    subjects.resources :activities, :name_prefix => "subject_"
    subjects.resources :units, :name_prefix => "subject_"
  end
  
  map.resources :levels do |levels|
    levels.resources :activities, :name_prefix => "subject_"
    levels.resources :units, :name_prefix => "subject_"
  end

  map.resources :users, :member => { :interface => :get }
  map.resources :users, :member => { :interface => :put }
  map.resources :users, :member => { :vendor_interface => :get }
  map.resources :users, :member => { :roles => :get }
  map.resources :users, :member => { :roles => :put }
  
  map.resources :users do |users|
    users.resources :activities, :name_prefix => "user_"
    users.resources :learners, :name_prefix => "user_", :member => { :sessions => :get, :ot_learner_data => :get  }
  end

  map.login  'login', :controller => 'session', :action => 'new'
  map.logout 'logout', :controller => 'session', :action => 'destroy'
  map.resource :session, :controller => 'session'
  
  # WISE step-type needs to be able to issue a GET to start a new session
  map.session 'session/create', :controller => 'session', :action => 'create'

  map.with_options :action => 'compare' do |compare|
    compare.compare_view ':controller/:id/compare/:other'
  end

  map.with_options :action => 'sail_jnlp', :requirements => {:nobundles => /nobundles|/} do |jnlp|
    jnlp.sail_jnlp_view ':controller/:id/sail_jnlp/:vid/:uid/view', :savedata => nil, :authoring => nil
    jnlp.sail_jnlp_preview ':controller/:id/sail_jnlp/:vid/:uid/preview', :savedata => nil, :authoring => nil, :nobundles => 'nobundles'
    jnlp.sail_jnlp_authoring ':controller/:id/sail_jnlp/:vid/:uid/authoring', :savedata => nil, :authoring => true, :nobundles => 'nobundles'
    jnlp.sail_jnlp_run ':controller/:id/sail_jnlp/:vid/:uid/:nobundles', :savedata => true, :authoring => nil, :nobundles => ''
    jnlp.sail_jnlp_run_report ':runnable/:rid/reports/:id/sail_jnlp', :controller => 'reports', :savedata => nil, :authoring => nil
  end
  
  map.with_options :action => 'html_export_jnlp', :requirements => {:nobundles => /nobundles|/} do |jnlp|
    jnlp.html_export_jnlp_view ':controller/:id/html_export_jnlp/:vid/:uid/view', :savedata => nil, :authoring => nil
    jnlp.html_export_jnlp_preview ':controller/:id/html_export_jnlp/:vid/:uid/preview', :savedata => nil, :authoring => nil, :nobundles => 'nobundles'
    jnlp.html_export_jnlp_authoring ':controller/:id/html_export_jnlp/:vid/:uid/authoring', :savedata => nil, :authoring => true, :nobundles => 'nobundles'
    jnlp.html_export_jnlp_run ':controller/:id/html_export_jnlp/:vid/:uid/:nobundles', :savedata => true, :authoring => nil, :nobundles => ''
    jnlp.html_export_jnlp_run_report ':runnable/:rid/reports/:id/html_export_jnlp', :controller => 'reports', :savedata => nil, :authoring => nil
  end

  map.with_options :action => 'otml' do |otml|
    otml.otml_view ':controller/:id/otml/:vid/:uid/view', :savedata => nil, :authoring => nil
    otml.otml_preview ':controller/:id/otml/:vid/:uid/preview', :savedata => nil, :authoring => nil, :nobundles => "nobundles"
    otml.otml_authoring ':controller/:id/otml/:vid/:uid/authoring', :savedata => nil, :authoring => true, :nobundles => "nobundles"
    otml.otml_run ':controller/:id/otml/:vid/:uid/:nobundles', :savedata => true, :authoring => nil, :nobundles => ''
    otml.otml_learner_run ':controller/:id/otml/:vid/:uid/:lid', :savedata => true, :authoring => nil, :nobundles => ''
    otml.otml_external_otrunk_activity_report 'external_otrunk_activities/:id/otml', :controller => 'external_otrunk_activities', :reporting => true
  end
  
  map.with_options :action => 'overlay_otml' do |otml|
    otml.overlay_otml_view ':controller/:id/overlay_otml/:vid/:uid/view', :savedata => nil, :authoring => nil
    otml.overlay_otml_preview ':controller/:id/overlay_otml/:vid/:uid/preview', :savedata => nil, :authoring => nil, :nobundles => "nobundles"
    otml.overlay_otml_authoring ':controller/:id/overlay_otml/:vid/:uid/authoring', :savedata => nil, :authoring => true, :nobundles => "nobundles"
    otml.overlay_otml_run ':controller/:id/overlay_otml/:vid/:uid/:nobundles', :savedata => true, :authoring => nil, :nobundles => ''
    otml.overlay_otml_learner_run ':controller/:id/overlay_otml/:vid/:uid/:lid', :savedata => true, :authoring => nil, :nobundles => ''
    otml.overlay_otml_external_otrunk_activity_report 'external_otrunk_activities/:id/overlay_otml', :controller => 'external_otrunk_activities', :reporting => true
  end

  map.activities 'activities/check_xhtml', :controller => 'activities', :action => 'check_xhtml'
  map.activities 'activities/check_image_url', :controller => 'activities', :action => 'check_image_url'
  
  map.resources :activities, :member => { :copy => :get }
  map.resources :activities, :member => { :usage => :get }
  map.resources :activities, :member => { :ot_learner_data => :get }
  map.resources :activities, :member => { :save_draft => :put }
  map.resources :activities, :member => { :run_report => :get }
  map.resources :activities do |activities|
    activities.resources :units, :name_prefix => "activity_"
    activities.resources :learners, :name_prefix => "activity_", :member => { :sessions => :get, :ot_learner_data => :get  }
    activities.resources :levels, :name_prefix => "activity_"
    activities.resources :subjects, :name_prefix => "activity_"
  end


  map.models 'models/check_image_url', :controller => 'models', :action => 'check_image_url'
  
  map.resources :models, :member => { :copy => :get }
  map.resources :models, :member => { :usage => :get }
  map.resources :models do |models|
    models.resources :units, :name_prefix => "model_"
    models.resources :learners, :name_prefix => "model_", :member => { :sessions => :get, :ot_learner_data => :get  }
    models.resources :levels, :name_prefix => "model_"
    models.resources :subjects, :name_prefix => "model_"
  end

  map.resources :external_otrunk_activities, :member => { :copy => :get, :usage => :get, :ot_learner_data => :get }
  map.resources :external_otrunk_activities, :member => { :run_report => :get }
  map.resources :external_otrunk_activities do |external_otrunk_activities|
    external_otrunk_activities.resources :reports, :name_prefix => "external_otrunk_activity_"
    external_otrunk_activities.resources :units, :name_prefix => "external_otrunk_activity_"
    external_otrunk_activities.resources :learners, :name_prefix => "external_otrunk_activity_", :member => { :sessions => :get, :ot_learner_data => :get  }
    external_otrunk_activities.resources :levels, :name_prefix => "external_otrunk_activity_"
    external_otrunk_activities.resources :subjects, :name_prefix => "external_otrunk_activity_"
  end
  
  map.notification 'notification/:action', :controller => 'notification'
  
  map.statistics 'statistics', :controller => 'statistics', :action => 'month', :months => 1
  map.statistics 'statistics/month/:months', :controller => 'statistics', :action => 'month'
  map.statistics 'statistics/:action', :controller => 'statistics'
  
  map.statistics 'scoring', :controller => 'scoring', :action => 'index'
  map.statistics 'scoring/:action', :controller => 'scoring'
  
  # Install the default route as the lowest priority.
#  map.connect ':controller/:action/:id'
#  map.connect ':controller/:action/:id.:format'

  # display the page#index controller for the default route
  map.home '', :controller => "home", :action => 'index'
  map.connect '', :controller => "home", :action => 'index'  

end

app/models/report.rb
class Report < ActiveRecord::Base
  set_table_name "#{RAILS_DATABASE_PREFIX}reports"
  include Changeable
  
  acts_as_replicatable
  
  self.extend SearchableModel

  belongs_to :user
  belongs_to :reportable, :polymorphic => true  
  belongs_to :otrunk_report_template
  has_and_belongs_to_many :report_types, :join_table => "#{RAILS_DATABASE_PREFIX}report_types_reports"
  
  @@searchable_attributes = %w{name description}
  class <<self
    def searchable_attributes
      @@searchable_attributes
    end
  end
  
  include OtrunkSystem
  include SdsRunnable

  validates_presence_of :name
  validates_uniqueness_of :name

  def short_name
    self.otrunk_report_template.short_name + '_for_' + self.reportable.short_name
  end

  def self.reportable_serialize_token
    ":"
  end

  def self.serialize_reportable(activity)
   return [activity.class.name.to_s,activity.id].join(reportable_serialize_token)
  end
  
  def reportable_s
    if self.reportable
      return Report.serialize_reportable(self.reportable)
    end
    return nil
  end

  def reportable_from_s(string)
    type,id= string.split(Report.reportable_serialize_token)
    
    if id.to_i > 0 && reportable_types.index(type.constantize)
      self.reportable=type.constantize.find(id.to_i)  
    else
      logger.error("Error: bad reportable: #{string}")
    end
    return self.reportable
  end

  def reportable_s=(rep)
    if rep.is_a? String
      self.reportable_from_s(rep)
    end
  end
  
  protected
  
  def validate
    # validate any report_types which have limit_to_one = true
    self.report_types.select{|rt| rt.limit_to_one}.each do |rep_type|
      reports = self.reportable.reports.select{|rep| (rep != self && rep.report_types.include?(rep_type))}
      if reports.size > 0
        errors.add("report_type", "Limited report type (#{rep_type.id}: #{rep_type.name}) already in use in #{reports.collect{|r| "#{r.id}: #{r.name}"}.join(", ")}")
      end
    end
  end

  def reportable_types
    [Activity,ExternalOtrunkActivity]
  end
end

app/models/report_type.rb
class ReportType < ActiveRecord::Base
  set_table_name "report_types"
  include Changeable
  
  acts_as_replicatable
  
  self.extend SearchableModel
  
  @@searchable_attributes = %w{uri name}
  class <<self
    def searchable_attributes
      @@searchable_attributes
    end
  end
  
  validates_presence_of :uri
  validates_uniqueness_of :uri
  
  has_and_belongs_to_many :reports, :join_table => "report_types_reports"
  belongs_to :user
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= error_messages_for :report %>

<p><span class="SectionTitle">Name: </span><%= form.text_field :name, :size => 72 %></p>
  
<p><span class="SectionTitle">Description </span><%= form.text_area :description, :cols => 72, :rows => 2 %></p>

<p><span class="SectionTitle">Public: </span><%= form.check_box :public %></p>

<p>
  <span class="SectionTitle">Select the activity: </span>
  <%= select(:report, :reportable_s, @activities) %>
</p>

<p>
  
  <span class="SectionTitle">Select the report template: </span>
  <% otrunk_report_templates = OtrunkReportTemplate.find(:all).collect {|i| ["#{i.id}: #{i.name}", i.id]} %>
  <%= form.select(:otrunk_report_template_id, otrunk_report_templates) %>
  
</p>

<p>Leave the following options blank unless you know what you're doing:</p>

<p><span class="SectionTitle">Custom sds offering id: </span><%= form.text_field :custom_offering_id, :size => 7 %></p>

<p><span class="SectionTitle">Custom sds workgroup id: </span><%= form.text_field :custom_workgroup_id, :size => 7 %></p>

<p>
  <span class="SectionTitle">Report Types: </span>
  <div style="padding-left: 50px">
  <% ReportType.find(:all, :order => :name).each do |r|  %>
    <input type="checkbox" name="report[report_type_ids][]" value="<%= r.id %>"
    <% if @report.report_types.include?(r) %> checked="checked" <% end %> />
    <%= r.name %>
    <br/>
  <% end %>
  </div>
</p>

app/views/reports/edit.html.erb
<%= render(:partial => 'shared/header', :locals => {
  :location => 'top',
  :runnable => nil,
  :function => 'Edit',
  :authorable_object => @report,
  :authorable_object_class => Report, 
  :all_viewable_objects => @all_viewable_reports, 
  :all_editable_objects => @all_editable_reports }) %>

<div class="pageEdit">
<% form_for(:report, :url => report_path(@report), :html => { :method => :put }) do |f| %>
  <div class="top">
    <div class='editbox'>
      <%= submit_tag "Save" %>
    </div>
  </div>
  <%= render :partial => 'form', :object => f %>
<% end %>
</div>

app/views/reports/index.html.erb
<%= render(:partial => 'shared/header', :locals => {
  :location => 'top',
  :runnable => false,
  :runnable_as_report => true,
  :function => 'Index',
  :authorable_object_class => Report, 
  :authorable_object_pages => @report_pages,
  :all_viewable_objects => @all_viewable_reports, 
  :all_editable_objects => @all_editable_reports }) %> 

<div class="activityList">
<table cellpadding="5" cellspacing="0" width="100%">
  <colgroup width="120px" />
  <colgroup  />
  
    <% for report in @reports %>
      <tr align="left" class="ListLine<%= cycle('0', '1') -%>">
        <td>
          <%= link_to 'Show', report_path(report), :title => 'Show the model type specification' %><br />
          <% restrict_to 'admin || manager' do %>
            <%= link_to 'Run Report', sail_jnlp_report_path(report),
            :title => "Start the report: #{report.name} as a Java Web Start application. The first time you run this it may take a while to startup as the program is downloaded and saved on your hard drive."  %> <br />
            
            <%= link_to 'Edit', edit_report_path(report), :title => "Make changes in #{report.name}." %><br />
            <%= link_to 'Copy', {:action => 'copy', :id => report, :page => params[:page] },
              :title => "Make a copy of the report: '#{report.name}' and start editing it." %><br />
            <%= link_to 'Delete', report_path(report), :confirm => "Are you sure you want to delete: #{report.name}?", :method => :delete %>

          <% end %>              
        </td>
        <td>
          <span class="listTitle"><%= report.id %>: <%= h(report.name) %></span><br />
          <%= h(truncate(report.description, 160)) %><br />
          <span class="listTitle">
            Types: <strong><%= report.report_types.collect{|rt| rt.name }.join(",") %></strong>, DIY Author: <strong><%= (report.user ? report.user.name : "") %></strong>, 
          </span>
        </td>
      </tr>
    <% end %>
</table>
</div>

app/views/reports/new.html.erb
<%= render(:partial => 'shared/header', :locals => {
  :location => 'top',
  :runnable => nil,
  :function => 'Create',
  :authorable_object => @report,
  :authorable_object_class => Report, 
  :all_viewable_objects => @all_viewable_reports, 
  :all_editable_objects => @all_editable_reports }) %>

<div class="pageEdit">
<% form_for(:report, :url => reports_path, :html => { :method => :post }) do |f| %>
  <div class="top">
    <div class='editbox'>
      <%= submit_tag "Create" %>
    </div>
  </div>
  <%= render :partial => 'form', :object => f %>
<% end %>
</div>

app/views/reports/show.html.erb
<%= render(:partial => 'shared/header', :locals => {
  :location => 'top',
  :runnable => nil,
  :function => 'Show',
  :authorable_object => @report,
  :authorable_object_class => Report, 
  :all_viewable_objects => @all_viewable_reports, 
  :all_editable_objects => @all_editable_reports }) %>

<p><span class="SectionTitle">Name: </span><%= @report.name%></p>
<p><span class="SectionTitle">DIY Author: </span><%= @report.user.name%></p>
<p><span class="SectionTitle">Public: </span><strong><%= boolean_to_yes_no(@report.public) %></strong></p>
<p><span class="SectionTitle">Description: </span><br /><%= @report.description %></p>
<p><span class="SectionTitle"><%= @report.reportable_type %>:</span> <%= @report.reportable_id %>: <%= @report.reportable.name %></p>  
<p><span class="SectionTitle">OTrunk Report Template:</span> <%= @report.otrunk_report_template.id %>: <%= @report.otrunk_report_template.name %> </p>
<p><span class="SectionTitle">Report Types:</span> <%= @report.report_types.collect{|rt| link_to(rt.name, report_type_path(rt)) }.join(" , ") %> </p>